### ISSUE TITLE
Errors at startup

### ISSUE THREAD

**Issue by pyluyten** [alphapapa/pocket-reader.el#10]
While starting, i have

    error in post-command-hook (global-display-line-numbers-mode-check-buffers) : error no Column named "Added")

So, i tried to disable the global linum mode. Now, i have

    Symbol's value as variable is void : request-token

**Comment by alphapapa** [comment]
This is probably a configuration problem. Can you reproduce it with emacs
-q?

**Comment by pyluyten** [comment]
tried `emacs -q`. So in scratch buffer i had to load pocket-reader. 

    (require 'package)
    (package-initialize)
    (require 'pocket-reader)

Then called `pocket-reader` . I have the same error

    Symbol's value as variable is void : request-token

I forgot to explain i have an empty buffer called *pocket-reader* coming with the error. Do i need to setq variables for login / passwd ?

**Comment by pyluyten** [comment]
The *Messages* buffer says something more

    pocket-lib--request: Symbol’s value as variable is void: request-token

**Comment by alphapapa** [comment]
I assume then that you weren't prompted to log in to Pocket. Please enable `debug-on-error` and provide the backtrace from when the error occurs.

**Comment by pyluyten** [comment]
i set the variable but i have not much Message

    Entering debugger...
    tabulated-list--column-number: No column named Added
    Error in post-command-hook (global-display-line-numbers-mode-check-buffers): (error "No column named Added")

My version is *GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)*

**Comment by alphapapa** [comment]
I can't find any reason for these problems.  Please reproduce it with `debug-on-error` enabled in an `emacs -q` session.  Note also that `global-display-line-numbers-mode` is probably unsuitable for `pocket-reader` buffers, but I don't know if it's part of the problem here.

I pushed a new commit for `pocket-reader` with minor fixes.  I doubt they are related to this problem, but please try with the new package when it's built in a few hours.

**Comment by pyluyten** [comment]
The new commit does not change , but debug-on-error on a clean emacs sessions provides more information

    Debugger entered--Lisp error: (void-variable request-token)
      pocket-lib--authorize()
      pocket-lib--request(get :data (:offset 0 :count 50 :detailType "complete" :state nil :favorite nil :tag nil :content-type nil :sort nil :search "" :domain nil :since nil) :sync t)
      pocket-lib-get(:detail-type "complete" :count 50 :offset 0 :search "" :state nil :favorite nil :tag nil)
      pocket-reader--get-items(nil)
      pocket-reader-search(nil)
      pocket-reader-refresh()
      pocket-reader-mode()
      pocket-reader()
      funcall-interactively(pocket-reader)
      call-interactively(pocket-reader record nil)
      command-execute(pocket-reader record)
      execute-extended-command(nil "pocket-reader" "pocket-reader")
      funcall-interactively(execute-extended-command nil "pocket-reader" "pocket-reader")
      call-interactively(execute-extended-command nil nil)
      command-execute(execute-extended-command)

**Comment by vinitunni** [comment]
I too am facing the same error now. Emacs27
This is the debug log

`Debugger entered--Lisp error: (void-variable request-token)
  pocket-lib--authorize()
  pocket-lib--request(get :data (:offset 0 :count 50 :detailType "complete" :state nil :favorite nil :tag nil :content-type nil :sort nil :search "" :domain nil :since nil) :sync t)
  pocket-lib-get(:detail-type "complete" :count 50 :offset 0 :search "" :state nil :favorite nil :tag nil)
  pocket-reader--get-items(nil)
  pocket-reader-search(nil)
  pocket-reader-refresh()
  pocket-reader-mode()
  pocket-reader()
  funcall-interactively(pocket-reader)
  call-interactively(pocket-reader record nil)
  command-execute(pocket-reader record)
  helm-M-x-execute-command(pocket-reader)
`

**Comment by vinitunni** [comment]
Hello,
For what it is worth, i delved a bit into the code and ran
`(if-let ((request-token (pocket-lib--request-token :force force))
               (access-token (pocket-lib--access-token request-token :force force)))
          (pocket-lib--save-access-token access-token)
        (error "Unable to authorize (request-token:%s)" request-token))`
Which gave me an authorization link. However, on trying to accept it in the browser, it redirects to https://getpocket.com/404?invalidurl=1
Could this be the reason why it isn't starting up?
