### ISSUE TITLE
Capture highlights

### ISSUE THREAD

**Issue by samspo** [alphapapa/pocket-reader.el#21]
Hello Adam,
Nice package. Works very well (as all your packages). Thanks!
Would be nice to be able to import the highlights done on getpocket (with org-capture, for example, in order to be able to refile the information where I want).
Seems possible if I believe: https://github.com/karlicoss/pockexport

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.

That's an interesting idea, but as that link seems to explain, it's not a feature intended to be publicly accessible, so I don't want to add code for it, because it might suddenly stop working someday (likely, considering Mozilla).

If you come up with some code that works, I'd be glad to link to it or document it as add-on code.

**Comment by samspo** [comment]
Thanks for the follow up!
