### ISSUE TITLE
FYI: keybinds (also Return) dosent work in Evil mode

### ISSUE THREAD

**Issue by zeltak** [alphapapa/pocket-reader.el#5]
Hi.

I never used pocket but since this package came from you i will definitely give it a shot!

just FYI i use evil-mode and RETURN does nothing unless i turn off EVIL

wonder if you can also consider adding org capture support to this, could be useful :D

best and thx again for all your amazing packages!!!!

Z

**Comment by alphapapa** [comment]
Hey Z!  Cool, I'd really appreciate your help testing.

Hm, I'm not sure what to do about the return key issue.  I don't use EVIL myself, so I don't know much about it.  I'm guessing that you need to switch to insert mode in the pocket-reader buffer?  Or may not insert mode, but some kind of passthrough mode?  IIRC in Spacemacs there's a mode that passes through keys to Emacs instead of using the EVIL binds, but I don't remember...  Let me know if you figure this out, and maybe I can do something about it, or at least document it in the readme.

> wonder if you can also consider adding org capture support to this, could be useful :D

Yeah, I've been doing that manually by copying the URL to the kill-ring and then doing the capture myself.  I was thinking yesterday about binding a key to do the capture from the pocket-reader buffer, but I'm not sure if that would belong in pocket-reader itself, because capturing pages depends on org-capture templates and configuration.  It also depends on org-web-tools, which is currently a dependency anyway, but I'm not sure if it should be.  So I might just add some example code to the readme to do this for users that want it.  If you have any ideas here, please let me know.

> best and thx again for all your amazing packages!!!!

And thanks for your help testing them!  I wish I had more testers like you!  :)

**Comment by alphapapa** [comment]
Going to go ahead and close this, but feel free to let me know if you figure anything about about using it with EVIL.  Thanks.

**Comment by jeffjewiss** [comment]
Hey, just wanted to stop in and mention that I've been configuring pocket-reader with an emacs setup that uses evil mode and you can disable evil mode specifically with pocket-reader by adding `(add-to-list 'evil-emacs-state-modes 'pocket-reader-mode)` to your config.

You could alternatively setup custom keybindings, but the above should allow you to use the built-in keybindings.

Cheers

**Comment by alphapapa** [comment]
Thanks!  I'll try to remember that for the next time that an EVIL user asks me about keybindings in one of my packages, which seems to happen regularly.  :)
